import turtle
wn = turtle.Screen()
wn.bgcolor("yellow")
turtle = turtle.Pen()
turtle.shape("turtle")
turtle.pensize(10)

turtle.down()
turtle.forward(50)
turtle.back(50)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.back(50)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.forward(25)
turtle.left(90)

turtle.pendown()
turtle.forward(100)
turtle.back(20)
turtle.right(180)
turtle.circle(30, 360)
